SimpleBlog/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SimpleBlog.Models;
using SimpleBlog.Models.ViewModels;
using WebMatrix.WebData;

namespace SimpleBlog.Controllers
{
    [Authorize(Roles = "Developer,Admin,User")]
    public class BlogController : Controller
    {
        private readonly Blog_Db_Entities _entities = new Blog_Db_Entities();

        [HttpGet]
        public ActionResult Create()
        {
            var blogPostVm = new BlogPostVm();
            blogPostVm.CategoryList = CategoryListVm();
            return View(blogPostVm);
        }

        [HttpGet]
        public ActionResult Index()
        {
            var data = _entities
                .BlogPosts
                .Include(x => x.BlogPostsPostCategories)
                .Include(x => x.BlogPostsPostTags)
                .Where(x => x.IsDeleted == false)
                .OrderByDescending(x => x.Id)
                .ToList();
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(true)]
        public ActionResult Create(BlogPostVm model, HttpPostedFileBase file, string submit)
        {
            try
            {
                string imageName = "";
                if (model.PostFormat == null)
                {
                    TempData["ErrorMsg"] = "Please select your post format";
                    return View(model);
                }
               
                if (string.IsNullOrEmpty(model.PostTitle))
                {
                    TempData["ErrorMsg"] = "Please enter Post Title";
                    return View(model);
                }
                if (model.PostFormat == 1)
                {
                    if (string.IsNullOrEmpty(model.PostContent))
                    {
                        TempData["ErrorMsg"] = "Please enter Post Description";
                        return View(model);
                    }
                }
                
                if (string.IsNullOrEmpty(model.ExcerptText))
                {
                    TempData["ErrorMsg"] = "Please enter Excerpt Text";
                    return View(model);
                }

                if (!model.CategoryList.Select(x => x.IsChecked).Any())
                {
                    TempData["ErrorMsg"] = "Please select at least one category";
                    return View(model);
                }

                if (file != null)
                {
                    long fileSize = file.ContentLength;
                    if (fileSize > 640000)
                    {
                        TempData["ErrorMsg"] = "Image file size can not be more that 512 Kb.";
                        return View(model);
                    }

                    string extension = Path.GetExtension(file.FileName);

                    if (extension != null && (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" ||
                                              extension.ToLower() == ".png"))
                    {
                        Guid imageId = Guid.NewGuid();
                        string location = Server.MapPath("~/BlogImages/");
                        var completeImageLocation = location + imageId + extension.ToLower();
                        imageName = imageId + extension.ToLower();
                        if (!Directory.Exists(location))
                        {
                            Directory.CreateDirectory(location);
                            file.SaveAs(completeImageLocation);
                        }
                        else
                        {
                            file.SaveAs(completeImageLocation);
                        }
                    }
                }

                switch (submit.ToLower())
                {
                    case "save draft":
                        {
                            model.IsDrafted = true;
                            model.IsApproved = false;
                            model.IsPublished = false;
                            model.IsDeleted = false;
                            break;
                        }
                    case "publish":
                        {
                            model.IsDrafted = false;
                            model.IsApproved = false;
                            model.IsPublished = true;
                            model.IsDeleted = false;
                            break;
                        }
                    default:
                        {
                            TempData["ErrorMsg"] = "Do you wanna publish this post or just save this post as a draft";
                            return View(model);
                        }
                }
                var userId = WebSecurity.GetUserId(User.Identity.Name);
                BlogPost post = new BlogPost();
                post.PostTitle = model.PostTitle;
                post.PostContent = model.PostContent;
                post.IsDrafted = model.IsDrafted;
                post.IsApproved = model.IsApproved;
                post.IsDeleted = model.IsDeleted;
                post.IsPublished = model.IsPublished;
                post.CreatedBy = userId;
                post.CreatedDate = DateTime.Today;
                post.UpdatedBy = userId;
                post.UpdatedDate = DateTime.Today;
                post.BlogPostsImageUrl = imageName;
                post.ExcerptText = model.ExcerptText;
                post.YoutubeVedioCodec = model.YoutudeUrlCodec;
                post.PostFormat = model.PostFormat;
                using (var dbContextTransactions = _entities.Database.BeginTransaction())
                {
                    try
                    {
                        _entities.BlogPosts.Add(post);
                        _entities.SaveChanges();

                        int postId = post.Id;

                        foreach (var category in model.CategoryList.Where(x => x.IsChecked))
                        {
                            BlogPostsPostCategory postCategory = new BlogPostsPostCategory();
                            postCategory.PostId = postId;
                            postCategory.CategoryId = category.Id;

                            _entities.BlogPostsPostCategories.Add(postCategory);
                            _entities.SaveChanges();
                        }

                        string[] allTagText = model.TagText.Split(',');
                        int tagId;
                        foreach (var tag in allTagText)
                        {
                            var tagDetails = _entities.BlogPostTags.FirstOrDefault(x => x.TagName == tag);
                            if (tagDetails == null)
                            {
                                BlogPostTag blogNewTag = new BlogPostTag();
                                blogNewTag.TagName = tag;
                                _entities.BlogPostTags.Add(blogNewTag);
                                _entities.SaveChanges();

                                tagId = blogNewTag.Id;
                            }
                            else
                            {
                                tagId = tagDetails.Id;
                            }

                            BlogPostsPostTag blogPostTag = new BlogPostsPostTag();
                            blogPostTag.TagId = tagId;
                            blogPostTag.PostId = postId;

                            _entities.BlogPostsPostTags.Add(blogPostTag);
                            _entities.SaveChanges();
                        }
                        dbContextTransactions.Commit();
                    }
                    catch (Exception)
                    {
                        dbContextTransactions.Rollback();
                        throw;
                    }
                }

                if (model.IsDrafted && !model.IsPublished)
                {
                    TempData["SuccessMsg"] = "Post Successfully drafted";
                    return RedirectToAction("Create");
                }
                if (!model.IsDrafted && model.IsPublished)
                {
                    TempData["SuccessMsg"] = "Post Successfully published";
                    return RedirectToAction("Create");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = ex.ToString();
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["ErrorMsg"] = "Plese select corectly";
                return RedirectToAction("Index");
            }
            var details = _entities.BlogPosts
                .Include(x => x.BlogPostsPostCategories)
                .Include(x => x.BlogPostsPostTags)
                .SingleOrDefault(x => x.Id == id);
            if (details == null)
            {
                TempData["ErrorMsg"] = "No Information found";
                return RedirectToAction("Index");
            }

            var blogVm = new BlogPostVm();

            blogVm.Id = details.Id;
            blogVm.PostTitle = details.PostTitle;
            blogVm.PostContent = details.PostContent;
            blogVm.IsDrafted = details.IsDrafted;
            blogVm.IsPublished = details.IsPublished;
            blogVm.IsApproved = details.IsApproved;
            blogVm.ExcerptText = details.ExcerptText;
            blogVm.YoutudeUrlCodec = details.YoutubeVedioCodec;
            blogVm.CreatedDate = details.CreatedDate.ToString();
            blogVm.CreatedBy = details.CreatedBy;
            blogVm.UpdatedDate = details.UpdatedDate.ToString();
            blogVm.UpdatedBy = details.UpdatedBy;

SimpleBlog/Controllers/BlogPostCategoriesController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using SimpleBlog.Models;
using SimpleBlog.Models.ViewModels;

namespace SimpleBlog.Controllers
{
    [Authorize(Roles = "Developer,Admin,User")]
    public class BlogPostCategoriesController : Controller
    {
        private readonly Blog_Db_Entities entities = new Blog_Db_Entities();

        public ActionResult Index()
        {
            BlogPostCategoryVm model = new BlogPostCategoryVm();
            model.PostCategoriesList = entities.BlogPostCategories.ToList();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult create(BlogPostCategoryVm model)
        {
            model.PostCategoriesList = entities.BlogPostCategories.ToList();
            if (ModelState.IsValid)
            {
                if (entities.BlogPostCategories.Where(x => x.CategoryName.ToLower().Trim() == model.CategoryName.ToLower().Trim()).Any())
                {
                    TempData["ErrorMsg"] = "There is already a Category on same name";
                    return PartialView("Blog_post_categories_partial", model);
                }
                BlogPostCategory category = new BlogPostCategory();
                category.CategoryName = model.CategoryName;
                entities.BlogPostCategories.Add(category);
                entities.SaveChanges();

                TempData["SuccessMsg"] = "Category created successfully";
                model.PostCategoriesList = entities.BlogPostCategories.ToList();
            }
            else
            {
                TempData["ErrorMsg"] = "Please enter Category name";
            }
            return PartialView("Blog_post_categories_partial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult delete(int id)
        {
            var model = new BlogPostCategoryVm();
            model.PostCategoriesList = entities.BlogPostCategories.ToList();
            try
            {
                var details = entities.BlogPostCategories.Find(id);
                if (details == null)
                {
                    TempData["ErrorMsg"] = "No data found";
                    return PartialView("Blog_post_categories_partial", model);
                }

                entities.BlogPostCategories.Remove(details);
                entities.SaveChanges();
                TempData["SuccessMsg"] = "Category Removed successfully";
                model.PostCategoriesList = entities.BlogPostCategories.ToList();
            }
            catch (Exception)
            {
                TempData["ErrorMsg"] = "You can not remove this category";
            }
            return PartialView("Blog_post_categories_partial", model);
        }
    }
}

SimpleBlog/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.Controllers
{
    [Authorize(Roles = "Developer,Admin,User")]
    public class DashboardController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SimpleBlog/Controllers/tagController.cs
using System.Linq;
using System.Web.Mvc;
using SimpleBlog.Models;
using SimpleBlog.Models.ViewModels;

namespace SimpleBlog.Controllers
{
    [Authorize(Roles = "Developer,Admin,User")]
    public class tagController : Controller
    {
        private Blog_Db_Entities _entities = new Blog_Db_Entities();

        [HttpGet]
        public ActionResult Index()
        {
            BlogPostTagVm tagVm = new BlogPostTagVm();
            tagVm.BlogPostTagList = _entities.BlogPostTags.ToList();
            return View(tagVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult create(BlogPostTagVm model)
        {
            model.BlogPostTagList = _entities.BlogPostTags.ToList();
            if (!ModelState.IsValid)
            {
                TempData["ErrorMsg"] = "Please enter tag text";
                return PartialView("_create_partial", model);
            }

            BlogPostTag tag = new BlogPostTag();
            tag.TagName = model.TagText;
            _entities.BlogPostTags.Add(tag);
            _entities.SaveChanges();
            TempData["SuccessMsg"] = "Tag Created Successfully";

            model.BlogPostTagList = _entities.BlogPostTags.ToList();

            return PartialView("_create_partial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult Delete(int? id)
        {
            var model = new BlogPostTagVm();
            model.BlogPostTagList = _entities.BlogPostTags.ToList();
            if (id == null)
            {
                TempData["ErrorMsg"] = "Please select category to delete";
                return PartialView("_create_partial", model);
            }
            var obj = _entities.BlogPostTags.Find(id);
            if (obj == null)
            {
                TempData["ErrorMsg"] = "Nothing's found";
                return PartialView("_create_partial", model);
            }
            _entities.BlogPostTags.Remove(obj);
            _entities.SaveChanges();
            TempData["SuccessMsg"] = "Tag removed successfully";
            model.BlogPostTagList = _entities.BlogPostTags.ToList();
            return PartialView("_create_partial", model);
        }
    }
}

SimpleBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Simple Blog | @ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/Content/Admin/assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/Content/Admin/assets/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/Content/Admin/assets/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/Content/Admin/assets/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/Content/Admin/assets/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="#" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>S</b>B</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Simple</b>Blog</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-envelope-o"></i>
                                <span class="label label-success">4</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have 4 messages</li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        <li>
                                            <!-- start message -->
                                            <a href="#">
                                                <div class="pull-left">
                                                    <img src="/Content/Admin/assets/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                                </div>
                                                <h4>
                                                    Support Team
                                                    <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                                </h4>
                                                <p>Why not buy a new awesome theme?</p>
                                            </a>
                                        </li>
                                        <!-- end message -->
                                    </ul>
                                </li>
                                <li class="footer"><a href="#">See All Messages</a></li>
                            </ul>
                        </li>
                        <!-- Notifications: style can be found in dropdown.less -->
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">10</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have 10 notifications</li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="footer"><a href="#">View all</a></li>
                            </ul>
                        </li>
                        <!-- Tasks: style can be found in dropdown.less -->
                        <li class="dropdown tasks-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-flag-o"></i>
                                <span class="label label-danger">9</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have 9 tasks</li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        <li>
                                            <!-- Task item -->
                                            <a href="#">
                                                <h3>
                                                    Design some buttons
                                                    <small class="pull-right">20%</small>
                                                </h3>
                                                <div class="progress xs">
                                                    <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                                                         aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="sr-only">20% Complete</span>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <!-- end task item -->
                                    </ul>
                                </li>
                                <li class="footer">
                                    <a href="#">View all tasks</a>
                                </li>
                            </ul>
                        </li>
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/Content/Admin/assets/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">Alexander Pierce</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="/Content/Admin/assets/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        Alexander Pierce - Web Developer
                                        <small>Member since Nov. 2012</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Followers</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Sales</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Friends</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="@Url.Action("SignOut","Accounts")" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="/Content/Admin/assets/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>Alexander Pierce</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
               
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                @Html.Partial("_SideBar")
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            
            <!-- Main content -->
            <section class="content">
                <!-- Default box -->
                @RenderBody()
                <!-- /.box -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1.0.0
            </div>
            <strong>Copyright &copy; @DateTime.Today.Year <a href="#">Nurul Haque</a>.</strong> All rights
            reserved.
        </footer>
        <!-- Control Sidebar -->
        
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="/Content/Admin/assets/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="/Content/Admin/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/Content/Admin/assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/Content/Admin/assets/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="/Content/Admin/assets/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
<script src="/Content/Admin/assets/dist/js/demo.js"></script>
@RenderSection("Scripts",false)
    <script>
  $(document).ready(function () {
      $('.sidebar-menu').tree();
  })
    </script>
</body>
</html>

SimpleBlog/Views/Shared/_SideBar.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">MAIN NAVIGATION</li>
    <li class="active">
        <a href="@Url.Action("Index","Dashboard")">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-clipboard"></i>
            <span>Post</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="@Url.Action("Create","Blog")"><i class="fa fa-circle-o"></i> Add New</a></li>
            <li><a href="@Url.Action("Index","Blog")"><i class="fa fa-circle-o"></i> All Post</a></li>
        </ul>
    </li>
    <li class="" id="Category">
        <a href="@Url.Action("Index","BlogPostCategories")">
            <i class="fa fa-th-list"></i> <span>Category</span>
        </a>
    </li>
    <li class="" id="Tags">
        <a href="@Url.Action("Index","tag")">
            <i class="fa fa-tags"></i> <span>Tags</span>
        </a>
    </li>
</ul>

SimpleBlog/Views/Shared/_fb_comments_plugin_partial.cshtml
<div id="fb-root"></div>
<script>
(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.12&appId=130859344194304&autoLogAppEvents=1';
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-comments" data-href="http://globedse.com" data-width="750" data-numposts="10"></div>